environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "4"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
test_script:
  - node --version
  - yarn version
  - yarn test
build: off
cache:
  - "%LOCALAPPDATA%\\Yarn"